backend:
  name: git-gateway
  branch: main # O la rama que uses (master/main)

locale: 'es'

media_folder: "public/images" # Donde se guardarán las fotos físicas
public_folder: "/images"      # Cómo se verá la ruta en el HTML/Markdown

collections:
  - name: "noticias"
    label: "Noticias y Avisos"
    folder: "content/noticias" # <--- CAMBIA ESTO por tu carpeta de .md
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título de la Noticia", name: "title", widget: "string" }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime" }
      - { label: "Imagen Principal", name: "image", widget: "image", required: false }

      - { label: "Contenido de la Noticia", name: "body", widget: "markdown" }
